# Generated by Django 5.2.12 on 2026-03-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('outerwear', 'Outerwear'), ('formal', 'Formal'), ('household', 'Household')], max_length=50),
        ),
    ]
