# Generated by Django 5.2.12 on 2026-03-15 09:12

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_valet_order_assigned_valet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMField(choices=[('scheduled', 'Scheduled'), ('dispatched', 'Dispatched'), ('picked_up', 'Picked Up'), ('at_cleaner', 'At Cleaner'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('dispatched', 'Dispatched'), ('picked_up', 'Picked Up'), ('at_cleaner', 'At Cleaner'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
